### get all

GET http://localhost:3000/inv

### get one

GET http://localhost:3000/inv/632d982ef12d3aa4f211dba7

###

POST http://localhost:3000/inv
Content-Type: application/json

{
    "title": "Barang",
    "user_id": "1",
    "item_id": "2"
}

### 

DELETE http://localhost:3000/inv/63302767653ad017f94696e2

###

PATCH http://localhost:3000/inv/632ee673ea165aa8ff388fd3
Content-Type: application/json

{
    "title": "apalah"
}

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "test4",
    "password": "afsadada"
}

###

GET http://localhost:3000/auth

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "test11",
    "password": "afsadada"
}